### ISSUE TITLE
Aux is a reserved filename in Windows

### ISSUE THREAD

**Issue by ste93cry** [gajus/react-aux#10]
I wanted to delete the `node_modules` folder and recreate it on one of my projects and I found out that `Aux` is a reserved filename on Windows, thus I cannot easily delete the `react-aux` folder. The only viable solution to delete it was in [this](https://stackoverflow.com/questions/21072767/cant-delete-a-folder-on-windows-7-with-a-trailing-space) Stackoverflow answer

`rd "\\?\C:\holds bad subdir" /s`

Maybe it would be possible to rename `Aux.js` to something else? For reference, here an explanation about the reserved filenames:

[Naming Files, Paths, and Namespaces](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx)
>CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

**Comment by Richo99** [comment]
[hg[](url)]([url]([url]([url](

> hghhhhhhhhhhhhh\



))))
