### ISSUE TITLE
Add note about JSX/React Fragments 

### ISSUE THREAD

**Issue by jimthedev** [gajus/react-aux#13]
Looks like this won't be needed much longer due to https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

This is good news so there should probably be a note about this.

**Comment by gajus** [comment]
> Thanks to Gajus Kuizinas and other contributors who prototyped the Fragment component in open source.

– https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

Thats Okay. My effort has been acknowledged. :-)

**Comment by jimthedev** [comment]
Haha nice
