### ISSUE TITLE
Git doesn't like indexing aux

### ISSUE THREAD

**Issue by NathanaelG1** [gajus/react-aux#16]
Not sure if I am simply doing something wrong, I have looked up this issue on other sites and didn't really find much. When I include this library in a project then upload that project to Github I get the error "Fatal Error: Could not find file '[path]/Aux.js.'" 

The only way for me to upload my project is to add aux.js to my gitignore and then simply having people install it when they pull the repo. I also tried just writing an aux.js file without installing it from npm and got the same error.

**Comment by gajus** [comment]
Sounds like a generic Git question. There is nothing special about react-aux.

Are you aware that React provides this functionality natively, though?

https://github.com/gajus/react-aux#if-you-are-using-react-162-or-higher

Just wrap your JSX in `<></>`

**Comment by NathanaelG1** [comment]
Thanks for the tip. I was not aware of this.
