### ISSUE TITLE
Support react 15

### ISSUE THREAD

**Issue by kof** [gajus/react-aux#9]
What if we actually support react 15 in this component, so that people who are still not migrated to React 16 can start using it?

**Comment by kof** [comment]
One way is to wrap with a div when in react 15.
Another way is to use an array and add the keys, even if they are just an iterator.

**Comment by gajus** [comment]
That would be just misleading and produce unexpected results when finally migrating to v16.

**Comment by kof** [comment]
Can you expand on this?

**Comment by gajus** [comment]
Suppose you are using v15 and you use `react-aux`, and you style your component something like `#foo > div > p`, where `#foo` is the parent component `div` is whatever the workaround wrapping element to mimick v16 behaviour, and `p` is the actual component wrapped in `Aux`. Once you upgrade to `v16`, this will break.

**Comment by kof** [comment]
Thats true in case of wrapping with the div.

**Comment by gajus** [comment]
Thats true in case of wrapping with whatever.

> Another way is to use an array and add the keys, even if they are just an iterator.

Seems too much effort.

There is no reason someone cannot upgrade to v16 who wants this feature.

**Comment by kof** [comment]
There is. Many libraries are not ready for 16, upgrade is not always trivial.

**Comment by gajus** [comment]
Not something I've run into practise.

I see this request as an edge case that will serve the benefit of very few.

I recommend simply creating `react-aux-legacy` project.

**Comment by kof** [comment]
Not sure though if there is any workaround to get it done without wrapping container.

**Comment by gajus** [comment]
> Not sure though if there is any workaround to get it done without wrapping container.

There is. I think. You could override `render` method, like `react-css-modules` do. However, thats why I said it is an overkill for something like this.
